apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: electricity_influx
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: electricity
      defaultBucket: electricity
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
